from models import (
    AgentResponse,
    Chunk,
    ChunksResponse,
    TextResponse,
    ThinkResponse,
)

MOCK_RESPONSE_1: list[AgentResponse] = [
    ThinkResponse(text="Thinking..."),
    ThinkResponse(text="Still thinking..."),
    ThinkResponse(text="Done thinking."),
    ChunksResponse(chunks=[Chunk(document_id="doc1", chunk_id="chunk1", title="Title 1", text="Text 1")]),
    TextResponse(text="# Bank Statement Converter\n\nThis repository holds a"),
    TextResponse(text=" Python Notebook script, `src/main.ipynb` to convert bank"),
    TextResponse(text=" statements into CSV files. To generate a CSV file for"),
    TextResponse(text=" your statements, simply put your e-bank statements into"),
    TextResponse(text=" the `statements` directory.[chunk1] You can find example"),
    TextResponse(text=" templates of statements that have been used to test these"),
    TextResponse(text=" scripts in the [assets](./assets) directory.\n\nAll"),
    TextResponse(text=" statements that go into the `statements` directory must"),
    TextResponse(text=" follow the following naming convention:\n`YYYY-MM.pdf`\n\nOnce"),
    TextResponse(text=" all the script finishes running within a notebook, a"),
    TextResponse(text=" `statement.csv` file will be generated in the `src`"),
    TextResponse(text=" directory. Your statement information would also all be"),
    TextResponse(text=" saved into a dataframe variable `df`, which you can"),
    TextResponse(text=" manipulate even after the run.\n\n## Script"),
    TextResponse(text=" Limitations\n\n**Unable to differentiate between"),
    TextResponse(text=" withdrawal**\nCurrently, both Deposit and Withdrawal"),
    TextResponse(text=" amounts are combined under the same column: `Amount`, as"),
    TextResponse(text=" there is currently no way for the current algorithm to"),
    TextResponse(text=" differentiate between the two. This is due to the"),
    TextResponse(text=" extraction process putting the values of a row all into"),
    TextResponse(text=" one since the delineator between a deposit and withdraw"),
    TextResponse(text=" is always a space, whereas a balance can always be"),
    TextResponse(text=" identified as the last number next to another number or"),
    TextResponse(text=" when the entry is the `C/F BALANCE`.\n\nFurthermore, since"),
    TextResponse(text=" multi-day transactions only show the balance at the end"),
    TextResponse(text=" of the day instead of it being recalculated after each"),
    TextResponse(text=" transaction, simply comparing the final end of day"),
    TextResponse(text=" balance to the amount deposited/withdrawn will not"),
    TextResponse(text=" work. A more advanced algorithm needs to be created to"),
    TextResponse(text=" allow for the calculation of which amounts are supposed"),
    TextResponse(text=" to be added/subtracted to get to the final value.\n\nThis"),
    TextResponse(text=" repository will be open to any contributions that could"),
    TextResponse(text=" get these scripts to overcome this limitation."), 
]

MOCK_RESPONSE_2: list[AgentResponse] = [
    ThinkResponse(text="Thinking..."),
    ThinkResponse(text="Still thinking..."),
    ThinkResponse(text="Done thinking."),
    ChunksResponse(chunks=[Chunk(document_id="doc1", chunk_id="chunk1", title="Title 1", text="Text 1")]),
    TextResponse(text="# Recycle & Restore Bash Command\n\nSince"),
    TextResponse(text=" deleting files on terminal is irreversible"),
    TextResponse(text=" and immediate, this shell command is meant"),
    TextResponse(text=" to simulate a recycling bin where you can"),
    TextResponse(text=" send your files/directories into a recycle"),
    TextResponse(text=" bin and restore them if ever you need them"),
    TextResponse(text=" again.[chunk1]\n\n <br/>\n\n## Recycle Script Details\nWhen"),
    TextResponse(text=" a file/directory is sent to the recycle"),
    TextResponse(text=" bin, it will be renamed to the following"),
    TextResponse(text=" to remove potential duplicity:  \n`[file_name]_[inode_number]`\n\nYou can"),
    TextResponse(text=" select where to have your recycle bin"),
    TextResponse(text=" directory with the `recycle_directory`"),
    TextResponse(text=" variable. Just make sure to update this"),
    TextResponse(text=" for the Restore Script too.\n\nA hidden file `.restore.info`,"),
    TextResponse(text=" containing the former location of the"),
    TextResponse(text=" recycled file, will be created at the end"),
    TextResponse(text=" of the script.\n\n### Available Options\n- `-v` :"),
    TextResponse(text=" Verbose mode\n- `-r` : Recursive remove mode"),
    TextResponse(text=" (for directories)\n- `-i` : Interactive mode\n\n###"),
    TextResponse(text=" Recycling Example\n```bash recycle.sh -iv"),
    TextResponse(text=" [file1] [file2] [directory3]```\n\n <br/>\n\n## Restore Script"),
    TextResponse(text=" Details\nOnly files within the `recyclebin`"),
    TextResponse(text=" can be restored. It will obtain the location the file"),
    TextResponse(text=" once was in the hidden `.restore.info` created"),
    TextResponse(text=" by the recycle command.\n\nRemember to make sure"),
    TextResponse(text=" the `recycle_directory` variable is the same as"),
    TextResponse(text=" what was inputted for the recycle command.\n\n### Available Options\n-"),
    TextResponse(text=" `-v` : Verbose mode\n- `-i` : Interactive mode\n\n### Restore"),
    TextResponse(text=" Example\n```bash restore.sh -iv [file1]_[inode] [file2]_[inode]"),
    TextResponse(text=" [directory3]_[inode]```\n\n <br/>\n\n## Limitations\n- Options must"),
    TextResponse(text=" be stated before any of the files/directories are"),
    TextResponse(text=" given\n- There is no error handling if a file with"),
    TextResponse(text=" the same inode number and name is recycled, as"),
    TextResponse(text=" these values are expected to be unique)")
]